---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
implicit:
  - Цена со скидкой должна быть всегда меньше основной цены
  - Если для товара скидка не задана, то должна выводиться только одна актуальная цена
  - При наличии скидки основная (старая) цена должна быть перечеркнута и иметь менее яркий цвет
  - Цена со скидкой должна быть выделена более контрастным цветом или крупным/жирным шрифтом
  - В блоке фильтров каталога должна быть предусмотрена кнопка «Сбросить все фильтры»
  - Название товара внутри корзины должно быть кликабельной ссылкой, ведущей на страницу этого товара
  - Пользователь должен иметь возможность изменять количество каждого товара прямо в корзине 
  - После оформления заказа содержимое корзины должно полностью очищаться, а счётчик товаров в корзине — сбрасываться
  - Если в корзине есть товары, при закрытии вкладки или браузера сайт должен предупреждать о потере данных сессии
  - Переключатель языка интерфейса должен визуально выделять выбранный на данный момент язык
